# Generated by Django 5.0.4 on 2024-05-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiotest',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='audiotest',
            name='text_to_pronounce',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
