# Generated by Django 5.0.4 on 2024-05-13 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_audioquestion_distractors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, default='No word provided', max_length=100, null=True)),
                ('distractors', models.CharField(default='Add words', max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='audiotest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listeningquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='listeningquestion',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='listeningquestion',
            name='test',
        ),
        migrations.RemoveField(
            model_name='listeningtest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='listeningtest',
            name='title',
        ),
        migrations.RemoveField(
            model_name='listeningtest',
            name='video_url',
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.word'),
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='current_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='questions',
            field=models.ManyToManyField(to='website.question'),
        ),
        migrations.AlterField(
            model_name='listeningtest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.category'),
        ),
        migrations.DeleteModel(
            name='AudioQuestion',
        ),
        migrations.DeleteModel(
            name='AudioTest',
        ),
    ]
