# Generated by Django 5.0.4 on 2024-05-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_listeningtest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningtest',
            name='questions',
            field=models.ManyToManyField(to='website.listeningquestion'),
        ),
    ]
