# Generated by Django 5.0.4 on 2024-05-13 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_listeningword_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.listeningword'),
        ),
    ]
