# Generated by Django 5.0.4 on 2024-05-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_grammarquestion_answeroption_grammartest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grammarquestion',
            old_name='correct_word',
            new_name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='grammarquestion',
            name='position',
        ),
    ]
